// sentinelpay-ui/src/views/Decisions.tsx
import { useEffect, useRef, useState } from "react";
import { Button } from "primereact/button";
import { InputSwitch } from "primereact/inputswitch";
import { ProgressSpinner } from "primereact/progressspinner";

import DecisionDetail from "../components/DecisionDetail";
import DecisionTable from "../components/DecisionTable";
import { fetchDecisions, type DecisionRecord } from "../api/decisions";

const Decisions = () => {
  const [decisions, setDecisions] = useState<DecisionRecord[]>([]);
  const [selected, setSelected] = useState<DecisionRecord | null>(null);
  const [loading, setLoading] = useState(false);
  const [lastRefresh, setLastRefresh] = useState("-");
  const [errorMessage, setErrorMessage] = useState("");
  const [autoRefresh, setAutoRefresh] = useState(true);
  const intervalRef = useRef<number | undefined>(undefined);

  const restoreScroll = (scrollX: number, scrollY: number) => {
    requestAnimationFrame(() => {
      window.scrollTo({ top: scrollY, left: scrollX, behavior: "auto" });
      requestAnimationFrame(() => {
        window.scrollTo({ top: scrollY, left: scrollX, behavior: "auto" });
      });
    });
  };

  const loadDecisions = async () => {
    const scrollX = window.scrollX;
    const scrollY = window.scrollY;
    setLoading(true);
    try {
      const data = await fetchDecisions();
      const sorted = [...data].sort(
        (a, b) => new Date(b.createdAt || 0).getTime() - new Date(a.createdAt || 0).getTime()
      );
      setDecisions(sorted);
      if (!selected && sorted.length) {
        setSelected(sorted[0]);
      }
      setErrorMessage("");
      setLastRefresh(new Date().toLocaleTimeString());
    } catch (error) {
      const message = error instanceof Error ? error.message : "Failed to load decisions";
      setErrorMessage(message);
    } finally {
      setLoading(false);
      restoreScroll(scrollX, scrollY);
    }
  };

  useEffect(() => {
    loadDecisions();
  }, []);

  useEffect(() => {
    if (!autoRefresh) {
      if (intervalRef.current) {
        window.clearInterval(intervalRef.current);
        intervalRef.current = undefined;
      }
      return;
    }

    if (!intervalRef.current) {
      intervalRef.current = window.setInterval(loadDecisions, 10000);
    }

    return () => {
      if (intervalRef.current) {
        window.clearInterval(intervalRef.current);
        intervalRef.current = undefined;
      }
    };
  }, [autoRefresh]);

  return (
    <>
      <div className="surface-card" style={{ marginBottom: 16 }}>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            flexWrap: "wrap",
            gap: 12
          }}
        >
          <div>
            <h2 className="section-title">Fraud Decisions</h2>
            <p className="subtle">Latest decisions stored by fraud-orchestrator.</p>
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              <InputSwitch checked={autoRefresh} onChange={(e) => setAutoRefresh(Boolean(e.value))} />
              <span className="subtle">Auto refresh (10s)</span>
            </div>
            <span className="subtle">Last refresh: {lastRefresh}</span>
            <Button label="Refresh" icon="pi pi-refresh" severity="secondary" onClick={loadDecisions} />
          </div>
        </div>
      </div>

      {loading ? (
        <div className="surface-card" style={{ display: "flex", justifyContent: "center" }}>
          <ProgressSpinner />
        </div>
      ) : (
        <>
          {errorMessage ? (
            <div className="surface-card" style={{ marginBottom: 16 }}>
              <p className="subtle">{errorMessage}</p>
            </div>
          ) : null}
          {!decisions.length ? (
            <div className="surface-card">
              <p className="subtle">No decisions yet. Submit a transaction and wait for the pipeline.</p>
            </div>
          ) : (
            <div className="decision-grid">
              <div className="surface-card">
                <DecisionTable decisions={decisions} selected={selected} onSelect={setSelected} />
              </div>
              <DecisionDetail decision={selected} />
            </div>
          )}
        </>
      )}
    </>
  );
};

export default Decisions;

// sentinelpay-ui/src/views/Decisions.vue
<template>
  <div class="surface-card" style="margin-bottom: 16px;">
    <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 12px;">
      <div>
        <h2 class="section-title">Fraud Decisions</h2>
        <p class="subtle">Latest decisions stored by fraud-orchestrator.</p>
      </div>
      <div style="display: flex; align-items: center; gap: 12px; flex-wrap: wrap;">
        <div style="display: flex; align-items: center; gap: 8px;">
          <InputSwitch v-model="autoRefresh" />
          <span class="subtle">Auto refresh (10s)</span>
        </div>
        <span class="subtle">Last refresh: {{ lastRefresh }}</span>
        <Button label="Refresh" icon="pi pi-refresh" severity="secondary" @click="loadDecisions" />
      </div>
    </div>
  </div>

  <div v-if="loading" class="surface-card" style="display: flex; justify-content: center;">
    <ProgressSpinner />
  </div>

  <div v-else>
    <div v-if="errorMessage" class="surface-card" style="margin-bottom: 16px;">
      <p class="subtle">{{ errorMessage }}</p>
    </div>
    <div v-if="!decisions.length" class="surface-card">
      <p class="subtle">No decisions yet. Submit a transaction and wait for the pipeline.</p>
    </div>
    <div v-else style="display: grid; grid-template-columns: 1.6fr 1fr; gap: 16px;">
      <div class="surface-card">
        <DecisionTable :decisions="decisions" :selected="selected" @select="setSelected" />
      </div>
      <DecisionDetail :decision="selected" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, ref, watch } from "vue";
import Button from "primevue/button";
import InputSwitch from "primevue/inputswitch";
import ProgressSpinner from "primevue/progressspinner";

import DecisionDetail from "../components/DecisionDetail.vue";
import DecisionTable from "../components/DecisionTable.vue";
import { fetchDecisions, type DecisionRecord } from "../api/decisions";

const decisions = ref<DecisionRecord[]>([]);
const selected = ref<DecisionRecord | null>(null);
const loading = ref(false);
const lastRefresh = ref("-");
const errorMessage = ref("");
const autoRefresh = ref(true);
let intervalId: number | undefined;

const restoreScroll = (scrollX: number, scrollY: number) => {
  requestAnimationFrame(() => {
    window.scrollTo({ top: scrollY, left: scrollX, behavior: "auto" });
    requestAnimationFrame(() => {
      window.scrollTo({ top: scrollY, left: scrollX, behavior: "auto" });
    });
  });
};

const loadDecisions = async () => {
  const scrollX = window.scrollX;
  const scrollY = window.scrollY;
  loading.value = true;
  try {
    const data = await fetchDecisions();
    decisions.value = data.sort(
      (a, b) => new Date(b.createdAt || 0).getTime() - new Date(a.createdAt || 0).getTime()
    );
    if (!selected.value && decisions.value.length) {
      selected.value = decisions.value[0];
    }
    errorMessage.value = "";
    lastRefresh.value = new Date().toLocaleTimeString();
  } catch (error) {
    const message = error instanceof Error ? error.message : "Failed to load decisions";
    errorMessage.value = message;
  } finally {
    loading.value = false;
    await nextTick();
    restoreScroll(scrollX, scrollY);
  }
};

const setSelected = (decision: DecisionRecord) => {
  selected.value = decision;
};

const startAutoRefresh = () => {
  if (intervalId) return;
  intervalId = window.setInterval(loadDecisions, 10000);
};

const stopAutoRefresh = () => {
  if (intervalId) {
    window.clearInterval(intervalId);
    intervalId = undefined;
  }
};

watch(autoRefresh, (enabled) => {
  if (enabled) {
    startAutoRefresh();
  } else {
    stopAutoRefresh();
  }
});

onMounted(async () => {
  await loadDecisions();
  if (autoRefresh.value) {
    startAutoRefresh();
  }
});

onBeforeUnmount(stopAutoRefresh);
</script>

<style scoped>
@media (max-width: 1100px) {
  div[style*="grid-template-columns"] {
    grid-template-columns: 1fr !important;
  }
}
</style>
