// sentinelpay-ui/src/views/Transactions.vue
<template>
  <TransactionForm />

  <div class="surface-card" style="margin-top: 16px;">
    <div style="display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 12px;">
      <div>
        <h2 class="section-title">Transaction History</h2>
        <p class="subtle">Recent ingested transactions stored by transaction-ingestor.</p>
      </div>
      <div style="display: flex; align-items: center; gap: 12px; flex-wrap: wrap;">
        <div style="display: flex; align-items: center; gap: 8px;">
          <InputSwitch v-model="autoRefresh" />
          <span class="subtle">Auto refresh (10s)</span>
        </div>
        <span class="subtle">Last refresh: {{ lastRefresh }}</span>
        <Button label="Refresh" icon="pi pi-refresh" severity="secondary" @click="loadTransactions" />
      </div>
    </div>
  </div>

  <div v-if="loading" class="surface-card" style="margin-top: 16px; display: flex; justify-content: center;">
    <ProgressSpinner />
  </div>

  <div v-else style="margin-top: 16px;">
    <div v-if="!transactions.length" class="surface-card">
      <p class="subtle">No transactions recorded yet. Submit a transaction above.</p>
    </div>
    <div v-else class="surface-card">
      <TransactionTable :transactions="transactions" />
    </div>
  </div>
</template>

<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref, watch } from "vue";
import Button from "primevue/button";
import InputSwitch from "primevue/inputswitch";
import ProgressSpinner from "primevue/progressspinner";

import TransactionForm from "../components/TransactionForm.vue";
import TransactionTable from "../components/TransactionTable.vue";
import { fetchTransactions, type TransactionResponse } from "../api/transactions";

const transactions = ref<TransactionResponse[]>([]);
const loading = ref(false);
const lastRefresh = ref("-");
const autoRefresh = ref(true);
let intervalId: number | undefined;

const loadTransactions = async () => {
  loading.value = true;
  try {
    const data = await fetchTransactions(50);
    transactions.value = data.sort(
      (a, b) => new Date(b.receivedAt).getTime() - new Date(a.receivedAt).getTime()
    );
    lastRefresh.value = new Date().toLocaleTimeString();
  } finally {
    loading.value = false;
  }
};

const startAutoRefresh = () => {
  if (intervalId) return;
  intervalId = window.setInterval(loadTransactions, 10000);
};

const stopAutoRefresh = () => {
  if (intervalId) {
    window.clearInterval(intervalId);
    intervalId = undefined;
  }
};

watch(autoRefresh, (enabled) => {
  if (enabled) {
    startAutoRefresh();
  } else {
    stopAutoRefresh();
  }
});

onMounted(async () => {
  await loadTransactions();
  if (autoRefresh.value) {
    startAutoRefresh();
  }
});

onBeforeUnmount(stopAutoRefresh);
</script>

// sentinelpay-ui/src/views/Transactions.tsx
import { useEffect, useRef, useState } from "react";
import { Button } from "primereact/button";
import { InputSwitch } from "primereact/inputswitch";
import { ProgressSpinner } from "primereact/progressspinner";

import TransactionForm from "../components/TransactionForm";
import TransactionTable from "../components/TransactionTable";
import { fetchTransactions, type TransactionResponse } from "../api/transactions";

const Transactions = () => {
  const [transactions, setTransactions] = useState<TransactionResponse[]>([]);
  const [loading, setLoading] = useState(false);
  const [lastRefresh, setLastRefresh] = useState("-");
  const [autoRefresh, setAutoRefresh] = useState(true);
  const intervalRef = useRef<number | undefined>(undefined);

  const loadTransactions = async () => {
    setLoading(true);
    try {
      const data = await fetchTransactions(50);
      setTransactions(
        [...data].sort((a, b) => new Date(b.receivedAt).getTime() - new Date(a.receivedAt).getTime())
      );
      setLastRefresh(new Date().toLocaleTimeString());
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadTransactions();
  }, []);

  useEffect(() => {
    if (!autoRefresh) {
      if (intervalRef.current) {
        window.clearInterval(intervalRef.current);
        intervalRef.current = undefined;
      }
      return;
    }

    if (!intervalRef.current) {
      intervalRef.current = window.setInterval(loadTransactions, 10000);
    }

    return () => {
      if (intervalRef.current) {
        window.clearInterval(intervalRef.current);
        intervalRef.current = undefined;
      }
    };
  }, [autoRefresh]);

  return (
    <>
      <TransactionForm />

      <div className="surface-card" style={{ marginTop: 16 }}>
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            flexWrap: "wrap",
            gap: 12
          }}
        >
          <div>
            <h2 className="section-title">Transaction History</h2>
            <p className="subtle">Recent ingested transactions stored by transaction-ingestor.</p>
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 12, flexWrap: "wrap" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              <InputSwitch checked={autoRefresh} onChange={(e) => setAutoRefresh(Boolean(e.value))} />
              <span className="subtle">Auto refresh (10s)</span>
            </div>
            <span className="subtle">Last refresh: {lastRefresh}</span>
            <Button label="Refresh" icon="pi pi-refresh" severity="secondary" onClick={loadTransactions} />
          </div>
        </div>
      </div>

      {loading ? (
        <div className="surface-card" style={{ marginTop: 16, display: "flex", justifyContent: "center" }}>
          <ProgressSpinner />
        </div>
      ) : (
        <div style={{ marginTop: 16 }}>
          {!transactions.length ? (
            <div className="surface-card">
              <p className="subtle">No transactions recorded yet. Submit a transaction above.</p>
            </div>
          ) : (
            <div className="surface-card">
              <TransactionTable transactions={transactions} />
            </div>
          )}
        </div>
      )}
    </>
  );
};

export default Transactions;
