// sentinelpay-ui/src/App.tsx
import { NavLink, Outlet } from "react-router-dom";

const App = () => {
  return (
    <div className="app-shell">
      <header className="navbar">
        <div className="navbar-inner">
          <div className="brand">
            <span className="brand-mark"></span>
            SentinelPay Ops Console
          </div>
          <nav className="nav-links">
            <NavLink to="/" className={({ isActive }) => (isActive ? "active" : undefined)}>
              Dashboard
            </NavLink>
            <NavLink to="/accounts" className={({ isActive }) => (isActive ? "active" : undefined)}>
              Accounts
            </NavLink>
            <NavLink to="/transactions" className={({ isActive }) => (isActive ? "active" : undefined)}>
              Simulate Transaction
            </NavLink>
            <NavLink to="/decisions" className={({ isActive }) => (isActive ? "active" : undefined)}>
              Fraud Decisions
            </NavLink>
            <NavLink to="/feedback" className={({ isActive }) => (isActive ? "active" : undefined)}>
              Feedback
            </NavLink>
            <NavLink to="/status" className={({ isActive }) => (isActive ? "active" : undefined)}>
              System Status
            </NavLink>
          </nav>
        </div>
      </header>

      <main className="app-main">
        <Outlet />
      </main>
    </div>
  );
};

export default App;

// sentinelpay-ui/src/App.vue
<template>
  <div class="app-shell">
    <header class="navbar">
      <div class="navbar-inner">
        <div class="brand">
          <span class="brand-mark"></span>
          SentinelPay Ops Console
        </div>
        <nav class="nav-links">
          <RouterLink to="/">Dashboard</RouterLink>
          <RouterLink to="/accounts">Accounts</RouterLink>
          <RouterLink to="/transactions">Simulate Transaction</RouterLink>
          <RouterLink to="/decisions">Fraud Decisions</RouterLink>
          <RouterLink to="/feedback">Feedback</RouterLink>
          <RouterLink to="/status">System Status</RouterLink>
        </nav>
      </div>
    </header>

    <main class="app-main">
      <RouterView />
    </main>

    <Toast position="top-right" />
  </div>
</template>

<script setup lang="ts">
import Toast from "primevue/toast";
</script>
