// sentinelpay-ui/src/components/ServiceStatusCard.tsx
import { Card } from "primereact/card";
import { Tag } from "primereact/tag";
import type { ServiceHealth } from "../api/health";

const ServiceStatusCard = ({ service }: { service: ServiceHealth }) => {
  const badgeText = service.status === "up" ? "Connected" : service.status === "down" ? "Disconnected" : "Unknown";

  const tagSeverity = service.status === "up" ? "success" : service.status === "down" ? "danger" : "warning";

  const lastChecked = service.lastChecked ? new Date(service.lastChecked).toLocaleTimeString() : "-";

  return (
    <Card className="status-card">
      <div className="status-header">
        <span className="status-title">{service.name}</span>
        <Tag severity={tagSeverity} value={badgeText} />
      </div>
      {service.url ? <p className="status-url">{service.url}</p> : <p className="status-url">No endpoint configured</p>}
      <div className="status-meta">
        <span className="subtle">Last check: {lastChecked}</span>
        {service.details ? <span className="subtle">{service.details}</span> : null}
      </div>
    </Card>
  );
};

export default ServiceStatusCard;

// sentinelpay-ui/src/components/ServiceStatusCard.vue
<template>
  <Card class="status-card">
    <template #content>
      <div class="status-header">
        <span class="status-title">{{ service.name }}</span>
        <Tag :severity="tagSeverity" :value="badgeText" />
      </div>
      <p class="status-url" v-if="service.url">{{ service.url }}</p>
      <p class="status-url" v-else>No endpoint configured</p>
      <div class="status-meta">
        <span class="subtle">Last check: {{ lastChecked }}</span>
        <span class="subtle" v-if="service.details">{{ service.details }}</span>
      </div>
    </template>
  </Card>
</template>

<script setup lang="ts">
import Card from "primevue/card";
import Tag from "primevue/tag";
import type { ServiceHealth } from "../api/health";

const props = defineProps<{ service: ServiceHealth }>();

const badgeText = props.service.status === "up"
  ? "Connected"
  : props.service.status === "down"
    ? "Disconnected"
    : "Unknown";

const tagSeverity = props.service.status === "up"
  ? "success"
  : props.service.status === "down"
    ? "danger"
    : "warning";

const lastChecked = props.service.lastChecked
  ? new Date(props.service.lastChecked).toLocaleTimeString()
  : "-";
</script>
